def build(bld):
    
    toolchain = bld.env["UsedToolchain"]
    if not toolchain:
        bld.fatal('Environment parameter "UsedToolchain" is not available! Make sure to provide the environment parameter "UsedToolchain" in the root wscript file of your project. e.g.: conf.env["UsedToolchain"] = "gccarmemb"')
    
    platform  = bld.env["UsedPlatform"]
    if not platform:
        bld.fatal('Environment parameter "UsedPlatform" is not available! Make sure to provide the environment parameter "UsedPlatform" in the root wscript file of your project. e.g.: conf.env["UsedPlatform"]  = "netx90"')
    
    comp_prefix = bld.get_name_prefix(
        toolchain = toolchain,
        platform  = platform)
    
    netx_studio_sources = [
        "Sources/FOC_APPL.c", 
    ]
    
    includes = [
        "Includes/",
    ]
    
    exported_includes = [
        "Includes/",
    ]
    
    defines = [
        "__NETX90",
        "_NETX_",
        #"DEMO_USE_POTENTIOMETER",
    ]
    
    exported_defines = [
    ]
    
    uses = [
        "netx_drv_sdk",
        "CMSIS_sdk",
        "mcl_sdk",
        "math_sdk",
        "hal_sdk",
    ]

    bld.stlib(
        target           = "foc_appl",
        name             = comp_prefix + "foc_appl",
        platform         = platform,
        toolchain        = toolchain,
        source           = netx_studio_sources,
        includes         = includes,
        defines          = defines,
        use              = uses,
        export_includes  = exported_includes,
        export_defines   = exported_defines,
    )
    
    bld.sdkcomponent(
        name            = "foc_appl_sdk",
        export_includes = includes,
        )